# ============================================================
# DIPDoc Backend — /report Route
# Generates structured clinical report data
# ============================================================

from flask import Blueprint, request, jsonify
from datetime import datetime

report_bp = Blueprint('report', __name__)

baseline_service = None
shap_engine = None
gemini_service = None


def init_report(bl_service, shap_svc, gem_service):
    global baseline_service, shap_engine, gemini_service
    baseline_service = bl_service
    shap_engine = shap_svc
    gemini_service = gem_service


@report_bp.route('/report/<user_id>', methods=['GET'])
def generate_report(user_id):
    """
    GET /report/<user_id>
    
    Generates a simplified Clinical Report focused on deviations.
    Returns structured JSON for client-side jsPDF generation.
    
    Query params:
        format: 'json' (default) or 'summary'
    """
    try:
        fmt = request.args.get('format', 'json')

        if not baseline_service:
            return jsonify({'error': 'Service not initialized'}), 500

        # Get baseline
        baseline = baseline_service.get_baseline(user_id)
        record_count = baseline_service.get_record_count(user_id)

        # Get latest sensors from most recent record
        records = baseline_service._store.get(user_id, [])
        latest = records[-1] if records else None

        sensors = latest.get('sensors', {}) if latest else {}
        events = latest.get('events', {}) if latest else {}
        status = latest.get('status', 'Normal') if latest else 'Normal'
        deviation = latest.get('deviation_score', 0) if latest else 0

        # SHAP analysis
        shap_result = None
        if shap_engine:
            shap_result = shap_engine.compute_local(sensors, events, baseline)

        # AI advice
        advice = ''
        if gemini_service:
            advice_result = gemini_service.get_advice(sensors, events, status)
            advice = advice_result['advice']

        # Build report
        report = {
            'report_id': f"RPT-{user_id}-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
            'generated_at': datetime.utcnow().isoformat(),
            'patient_id': user_id,
            'baseline_period_days': 14,
            'baseline_records': record_count,

            'current_status': status,
            'deviation_score': deviation,

            'vitals': {
                'breath_quality': {
                    'current': sensors.get('breath_quality', 'N/A'),
                    'baseline': baseline.get('breath_quality', {}).get('mean', 'N/A'),
                    'normal_range': '85-100%',
                    'unit': '%'
                },
                'voice_stress': {
                    'current': sensors.get('voice_stress', 'N/A'),
                    'baseline': baseline.get('voice_stress', {}).get('mean', 'N/A'),
                    'normal_range': '0-25',
                    'unit': 'index'
                },
                'hydration': {
                    'current': sensors.get('hydration', 'N/A'),
                    'baseline': baseline.get('hydration', {}).get('mean', 'N/A'),
                    'normal_range': '55-70%',
                    'unit': '%'
                },
                'gas_raw': {
                    'current': sensors.get('gas_raw', 'N/A'),
                    'baseline': baseline.get('gas_raw', {}).get('mean', 'N/A'),
                    'normal_range': '150-300 ppm',
                    'unit': 'ppm'
                },
                'impedance': {
                    'current': sensors.get('impedance', 'N/A'),
                    'baseline': baseline.get('impedance', {}).get('mean', 'N/A'),
                    'normal_range': '450-570 Ω',
                    'unit': 'Ω'
                }
            },

            'events': {
                'cough_detected': events.get('cough_detected', False),
                'voice_strain': events.get('voice_strain', False),
                'low_hydration': events.get('low_hydration', False)
            },

            'shap_analysis': shap_result,
            'ai_advice': advice,

            'clinical_note': (
                f"This report covers deviations from the patient's {record_count}-record "
                f"personal baseline over {14} days. Focus is on significant deviations "
                f"rather than raw numbers. Current status: {status} "
                f"(deviation score: {deviation}%)."
            ),

            'disclaimer': (
                "This report is auto-generated by DIPDoc and should be reviewed "
                "by a qualified healthcare professional. It is intended as a "
                "monitoring aid, not a diagnostic tool."
            )
        }

        if fmt == 'summary':
            return jsonify({
                'status': status,
                'deviation_score': deviation,
                'top_concern': shap_result['top_factor'] if shap_result else 'N/A',
                'advice': advice,
                'records': record_count
            }), 200

        return jsonify(report), 200

    except Exception as e:
        return jsonify({'error': str(e)}), 500
